name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build vib
      run: |
        go get ./...
        make build

    - name: Build plugins
      run: |
        go get ./...
        make build-plugins
        tar cvf plugins.tar.xz build/plugins

    - uses: actions/upload-artifact@v4
      with:
         name: Vib
         path: |
            build/vib
            plugins.tar.xz
