name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libbtrfs-dev make gcc gcc-aarch64-linux-gnu

    - name: Build vib
      run: |
        go get ./...
        go get github.com/ebitengine/purego
        make BINARY_NAME=vib-amd64 build
        mv build/vib-amd64 ./
        make clean
        GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc make BINARY_NAME=vib-arm64 build
        mv build/vib-arm64 ./

    - name: Build plugins
      run: |
        go get ./...
        make build-plugins
        tar czvf plugins-amd64.tar.gz build/plugins
        make clean
        GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc make build-plugins
        tar czvf plugins-arm64.tar.gz build/plugins

    - uses: actions/upload-artifact@v4
      with:
         name: Vib
         path: |
            vib*
            plugins*.tar.gz
